### ISSUE TITLE
Does this support Plasma 6?

### ISSUE THREAD

**Issue by Yasand123** [xmaciek/kdegraphics-thumbnailer-dds#2]

**Comment by xmaciek** [comment]
yes

**Comment by Yasand123** [comment]
I wonder what the issue is, I compiled the package via [the AUR](https://aur.archlinux.org/packages/kdegraphics-thumbnailer-dds-git) (Arch User Repository) but Dolphin still does not show thumbnails for dds files. The package compiled from source.

**Comment by xmaciek** [comment]
Alright let's try figuring this out, please try the following:
1) After installing package restart every dolphin instance, so dolphin can be aware of the thumbnailer
2) Check whether thumbnailer is enabled, please go to `configure`->`configure dolphin`->`interface`->`previews`->`Microsoft DirectDraw surface`
3) On older plasma5 I had an issue where default install dir was incorrect, but that went away with newer version. I hope this is not a regression. On plasma 6.1 & Arch I have these 2 paths
`/usr/lib/qt6/plugins/ddsthumbnail.so`
`/usr/lib/qt6/plugins/kf6/thumbcreator/ddsthumbnail.so`
4) Maybe you have some image format that is not currently handled by the thumbnailer? Maybe I can add support for it?

Please let me know if this is any help to you.

**Comment by Yasand123** [comment]
> Microsoft DirectDraw surface

Yeah, that was it. I was just looking for "dds". I completely forgot dds stands for that. Sorry 🫣 And thank you so much for this tool. It's crucial for game development/modding.
